name: 'vue-upgrade'
description: 'vue upgrade'
author: 'Ryo Ota'
runs:
  using: 'composite'
  steps:
  - run: |
      set -xeu
      sudo npm install -g @vue/cli
      vue upgrade
      ls -l
      git status
    shell: bash
