name: 'vue-upgrade'
description: 'vue upgrade'
author: 'Ryo Ota'
inputs:
  github-token:
    description: GitHub Token
    required: true
runs:
  using: 'composite'
  steps:
  - run: |
      set -xeu
      # echo Y | npx -p @vue/cli vue upgrade
      touch new_file
      ls -l
      git status
      git checkout -b actions/vue-upgrade
      git config --global user.email "github-actions[bot]@users.noreply.github.com"
      git config --global user.name "github-actions[bot]"
      # git add package*.json
      git add new_file
      git commit -m 'vue upgrade'
      git push -fu origin actions/vue-upgrade
      git log
      export GITHUB_TOKEN=$(node -p "process.env['INPUT_GITHUB-TOKEN']")
      gh auth login
      gh pr create --base actions/vue-upgrade --title 'vue upgrade'
    shell: bash
  - run: echo 'hello!'
    shell: bash
