name: 'vue-upgrade'
description: 'vue upgrade'
author: 'Ryo Ota'
runs:
  using: 'composite'
  steps:
  - run: |
      set -xeu
      sudo npm i -g @vue/cli
      sudo vue upgrade
      # echo Y | npx @vue/cli vue upgrade
      ls -l
      git status
    shell: bash
