name: 'vue-upgrade'
description: 'vue upgrade'
author: 'Ryo Ota'
runs:
  using: 'composite'
  steps:
  - run: |
      set -xeu
      echo Y | npx -p @vue/cli vue upgrade
      ls -l
      git status
    shell: bash
